### PR TITLE
Docs: Add Iterative chaining design

### PR DESCRIPTION
**Pull request by JakobJingleheimer**

### CODE REVIEW

**Comment by GeoffreyBooth** [comment]
I just see four empty files. The current design doc should be one of them, and we should update the README to link to it.

I don’t think this PR should add placeholders and then another PR adds the contents; that’s how we end up with a “Coming Soon” page that never goes away if someone never gets around to writing the actual design doc. So maybe let’s remove the empty files and the PR that adds those design docs can create the files?

**Comment by JakobJingleheimer** [comment]
@GeoffreyBooth oh, I thought you suggested in the meeting I do this.

I have the two chaining proposal docs mostly done (stashed in my local). I can finish them and include in this PR if we want to wait to re-jig.

I figured the intention was to first update the structure, since multiple people will consume it (and this sort of unblocks them). Plus Derek needs a place for his proposal to go (it would be more work to move it after than for the folder to already exist).

**Comment by GeoffreyBooth** [comment]
Sorry I was thinking the initial PR would just rename the existing `design.md` and update the README link, and that’s it. Then when the second design doc is added, it doesn’t need to change anything about the first one.

**Comment by GeoffreyBooth** [comment]
@JakobJingleheimer do you mind splitting out the updates to the recursive design to be its own PR?

**Comment by JakobJingleheimer** [comment]
Sure. I'm away til Sunday; I can do it then.

**Pull request merged**
