### PR TITLE
Add jest-light-runner

### PR DESCRIPTION
**Pull request by GeoffreyBooth**

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Uh note that it's not a loader, it just can be used with loaders to do what jest does by using the VM module.

**Comment by GeoffreyBooth** [comment]
> Uh note that it’s not a loader, it just can be used with loaders to do some of the things that jest does by using the VM module.

That’s fine, this is a list of “related projects,” not a list of loaders.

Is there a high-level explanation for how it does what it does? It’s not using the loader API, I assume, so how does it add the Jest globals and do functional mocking and the other Jest features that it supports?

**Comment by nicolo-ribaudo** [comment]
Ok, to be more specific... It does nothing (that's why I initially replied to this issue, I don't know if it "fits" in this list). It just uses `import()` to load the test files, after attaching the Jest globals to `globalThis`.

Its relationship with loaders is just that it's (short) documentation shows that you can replace some of the Jest features, that Jest implements with `vm.Moduls`, with some loaders (that already exists, they were created by other people and not specifically for jest-light-runner).

It might add more value to add the loaders its README me tions to this list (ts-node and esmock).

However, it might be helpful to mention this package next to the Jest tracking issue link above in this file, for people who want to quickly now how to have a fully-compatible ESM environment when using Jest.

**Comment by GeoffreyBooth** [comment]
Thanks. I think it’s good to document how people are _already_ solving some of the problems on our list, like mocking, because those existing solutions are things we very much want to be aware of as we continue to develop the loaders API.

**Review by JakobJingleheimer — APPROVED** [review]

**Pull request merged**
